export const CLIENT_CONFIG = Object.freeze({
  appName: "KALOT ERP",
  tagline: "Interlocking Paver Block Management",
  poweredBy: "Powered by Rajratan ERP",
  companyName: "KALOT CEMENT PRODUCT / Kalot Industries",
  address: "Jaipur, Rajasthan",
  location: "Jaipur, Rajasthan",
  phone: "+91 9828685619",
  email: "kalotindustry@gmail.com",
  ownerName: "MH Kalot",
  ownerDesignation: "Owner",
  gstin: "GSTIN pending",
  industry: "Interlocking Paver Block Manufacturing",
  languagePreference: "Hindi-friendly",
  factoryCount: 3,
  locale: "en-IN",
  currency: "INR",
  brandInitials: "KE",
});
