export const SHEET_SCHEMAS = Object.freeze({
  Config: ["Key", "Value", "Updated_At"],
  Users: [
    "User_ID",
    "Email",
    "Name",
    "Role",
    "Factory_IDs",
    "Permissions",
    "Status",
    "Created_At",
    "Updated_At",
  ],
  Opening_Stock: [
    "Factory_ID",
    "Opening_ID",
    "Date",
    "Product_Size",
    "Color",
    "Blocks",
    "Brass",
    "Adjustment_Type",
    "Notes",
    "Created_At",
  ],
  Opening_Material_Stock: [
    "Factory_ID",
    "Date",
    "Material",
    "Quantity",
    "Unit",
    "Unit_Cost",
    "Total_Value",
  ],
  Production_Log: [
    "Factory_ID",
    "Production_ID",
    "Date",
    "Product_Size",
    "Total_Blocks",
    "Brass",
    "Mortar_Cement",
    "Color_Cement",
    "Total_Cement",
    "Greet_Tons",
    "Powder_Tons",
    "Chemical_Litres",
    "Yellow_Kg",
    "Red_Kg",
    "Black_Kg",
    "Total_Pigment_Kg",
    "Reti_Ghamela",
    "Plastic_Ml",
    "Misc_Expenses",
    "Labour_Cost",
    "Total_Daily_Cost",
    "Cost_Per_Block",
    "Notes",
    "Created_At",
    "Updated_At",
  ],
  Production_Variants: [
    "Factory_ID",
    "Variant_ID",
    "Production_ID",
    "Date",
    "Product_Size",
    "Color",
    "Blocks",
    "Brass",
    "Cost_Per_Block",
    "Created_At",
  ],
  CRM_Log: [
    "Factory_ID",
    "CRM_Order_ID",
    "Date",
    "Client_Name",
    "Phone",
    "Location",
    "Color",
    "Order_Brass",
    "Order_Blocks",
    "Rate_Per_Brass",
    "Order_Value",
    "Status",
    "Notes",
    "Created_At",
    "Product_Size",
    "Priority",
    "Due_Date",
  ],
  Dispatch_Log: [
    "Factory_ID",
    "Dispatch_ID",
    "CRM_Order_ID",
    "Date",
    "Client_Name",
    "Color",
    "Dispatch_Brass",
    "Dispatch_Blocks",
    "Transport_Type",
    "Driver_Contact",
    "Vehicle_Number",
    "Freight_Amount",
    "Revenue",
    "Notes",
    "Created_At",
    "Product_Size",
  ],
  QC_Log: [
    "Factory_ID",
    "QC_ID",
    "QC_Group_ID",
    "Date",
    "Color",
    "Broken_Blocks",
    "Cost_Per_Block",
    "QC_Loss",
    "Reason",
    "Notes",
    "Created_At",
    "Product_Size",
  ],
  Customer_Payments: [
    "Factory_ID",
    "Payment_ID",
    "CRM_Order_ID",
    "Date",
    "Client_Name",
    "Amount",
    "Payment_Source",
    "Reference",
    "Notes",
    "Created_At",
  ],
  Stock_Thresholds: [
    "Factory_ID",
    "Threshold_ID",
    "Product_Size",
    "Color",
    "Minimum_Blocks",
    "Updated_At",
  ],
  Vendor_Ledger: [
    "Factory_ID",
    "Vendor_Entry_ID",
    "Date",
    "VendorName",
    "Material",
    "Type",
    "Quantity",
    "Unit",
    "Amount",
    "PaymentSource",
    "Notes",
    "Created_At",
  ],
  Payroll_Log: [
    "Factory_ID",
    "Payroll_Entry_ID",
    "Date",
    "Worker_Name",
    "Entry_Type",
    "Product_Size",
    "Pieces",
    "Rate_Per_Piece",
    "Amount",
    "Payment_Source",
    "Notes",
    "Created_At",
  ],
  CashFlow_Log: [
    "Factory_ID",
    "CashFlow_ID",
    "Date",
    "Type",
    "Source",
    "Amount",
    "Description",
    "Linked_Module",
    "Linked_ID",
    "Notes",
    "Created_At",
  ],
  External_Material_Usage: [
    "Factory_ID",
    "Date",
    "Material",
    "Quantity",
    "Unit",
    "Reference",
    "Notes",
  ],
  Bills_Log: [
    "Factory_ID",
    "Bill_ID",
    "Document_Type",
    "Invoice_No",
    "Date",
    "CRM_Order_ID",
    "Dispatch_ID",
    "Client_Name",
    "Client_Address",
    "Place_Of_Supply",
    "Item",
    "HSN",
    "Quantity_Brass",
    "Quantity_Blocks",
    "Rate",
    "Vehicle_No",
    "Transport_Type",
    "Taxable_Amount",
    "CGST",
    "SGST",
    "IGST",
    "Round_Off",
    "Final_Amount",
    "Notes",
    "Status",
    "Created_At",
  ],
  Activity_Log: [
    "Factory_ID",
    "Timestamp",
    "Module",
    "Action",
    "Description",
    "User_Email",
  ],
});

export const PUBLIC_SHEET_NAMES = Object.freeze(
  Object.keys(SHEET_SCHEMAS).filter(
    (name) => !["Config", "Users"].includes(name),
  ),
);

export function assertSheetName(sheetName, { allowConfig = false } = {}) {
  if (
    typeof sheetName !== "string" ||
    !Object.hasOwn(SHEET_SCHEMAS, sheetName) ||
    (!allowConfig && ["Config", "Users"].includes(sheetName))
  ) {
    const error = new Error("Invalid sheet name.");
    error.statusCode = 400;
    throw error;
  }

  return sheetName;
}
